### ISSUE TITLE
project setup

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/Capstone-Project#1]
## Value statement - a requirement, not a solution
As a user 
I need a navbar
so that i can navigate around

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/74617403/197206611-44122ea3-973d-4409-a6bd-03c7b9e6a244.png)

## Acceptance criteria
- [ ] the App should have a Header
- [ ] the App should have a navbar
- [ ] 4 possible pages

## Tasks
- [ ] add the Header
- [ ]  add all empty pages
- [ ] create the navbar with an active status
- [ ] link all pages to the navbar

## Size
small
