### ISSUE TITLE
userStory marker

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/Capstone-Project#11]
## Value statement - a requirement, not a solution
As a user
I want a marker where i clicked on the map
so that i can see the position easier 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/74617403/198528294-6df899fa-9d98-49e0-9955-2e03abe4e6cb.png)

## Acceptance criteria
- [ ] a marker on the map on the position i clicked
- [ ] the marker should be saved after the refresh

## Tasks
- [ ] add a marker onClick
- [ ] add the marker to the localStorage

## Size
big
