### ISSUE TITLE
marker-popup

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/Capstone-Project#15]
## Value statement - a requirement, not a solution
As a user
I want to see some information on the marker
so that i quickly can get some info's about that spot

## Acceptance criteria
- [ ] the marker should have a popup with information

## Tasks
- [ ] add a popup to the marker
- [ ] let the popup show added info's

## Size
medium
