### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/Capstone-Project#17]
## Value statement - a requirement, not a solution
As a user
I want that all my data is accessible all over the place
so that i can use this app on Vacation

## Acceptance criteria
- [ ] the app needs a backend with mongoDB
- [ ] all CRUD functions should work with the backend

## Tasks
- [ ] install mongoDB
- [ ] make the CRUD functions work

## Size
large
