### ISSUE TITLE
cloudinary

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/Capstone-Project#23]
## Value statement - a requirement, not a solution
As a user
I want a picture gallery
so that i can upload images 

## Acceptance criteria
- [ ] possibility to upload images from device
- [ ] display image on each card
- [ ] display all uploaded images on one site

## Tasks
- [ ] add a new input to upload images
- [ ] store them in cloudinary
- [ ] display image on each Card
- [ ] fetch every image on one site

## Size
medium
