### ISSUE TITLE
userStory

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/Capstone-Project#3]
## Value statement - a requirement, not a solution
As a user 
I want to see cards with the information i added via the form
so that i can view them when i need them

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/74617403/197555916-19c54815-cc83-4f22-9d8a-3f838e13ce88.png)

## Acceptance criteria
- [ ] i want to see cards with information i added through the form
- [ ] i want to see the cards inside the List page

## Tasks
- [ ] add cards with info inside the List page

## Size
medium
