### ISSUE TITLE
userStory Map

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/Capstone-Project#9]
## Value statement - a requirement, not a solution
As a user
I want a map in the form
so that i can find the location 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/74617403/198522097-63abc260-13fb-48a7-9604-06528c50c8a2.png)

## Acceptance criteria
- [ ] a map which is zoom and scroll able
- [ ] the map should be on the form page

## Tasks
- [ ] add a map into the form page
- [ ] make the map scroll and zoom able

## Size
medium
